### ISSUE TITLE
No assignment done on this line, so I was wondering what it was for.

### ISSUE THREAD

**Issue by IIYAMA12** [VincentKempers/wafs#11]
https://github.com/VincentKempers/wafs/blob/4807d2437a52e3bd9ad3fe5863ea5eba62a741ea/app/static/js/script.js#L63

Just wondering what line 63 is used for. (Might be something I do not understand about js)

**Comment by VincentKempers** [comment]
fixed! it didn't do anything  ¯\_(ツ)_/¯
