### ISSUE TITLE
Anonieme functies

### ISSUE THREAD

**Issue by Alexvanderwal** [VincentKempers/wafs#3]
In je code zie ik dat je je functies geen naam geeft, en ze dus anoniem houdt.
Het zou misschien handig kunnen zijn om deze toch een naam te geven, zodat je errors deze naam weergeven, en je doelgerichter kan zoeken. Tevens is dit een good practice volgens: https://github.com/airbnb/javascript#functions

**Comment by VincentKempers** [comment]
heb het enigzins toegevoegd ! ik ga meer aan de die guidelines doen.
