### ISSUE TITLE
Onnodige functie call

### ISSUE THREAD

**Issue by Alexvanderwal** [VincentKempers/wafs#4]
https://github.com/VincentKempers/wafs/blob/master/app/static/js/script.js#L20
In deze functie zet je de `window.hash` op `#start` als er geen hash is, roept daarna de `sections.toggle` functie aan, en voegt vervolgens een eventlistener toe die dezelfde functie uitvoert wanneer de hash verandert.
Dus, zou het niet beter te zijn om eerst de evenlistener toe te voegen, en daarna de window.hash te veranderen? Op deze manier hoef je de functie niet handmatig aan te roepen.
aldus:
`init: function(){
window.addEventListener('hashchange', function(event) {sections.toggle(window.location.hash}
if (window.location.hash === '') {
        window.location.hash = '#start';
      }
}`

**Comment by VincentKempers** [comment]
Niet gebruikt voor de fix. Want het gebeurt dan nu voor de change en in je voorbeeld gebeurt het in de 'hashchange'.
